name: a
version: 0.0.0
synopsis: Test case A
author: David Kraeutmann <kane@kane.cx>
build-tools: 
  - c2hs

default-extensions:
  - ForeignFunctionInterface
dependencies:
  - base >= 4.9 && < 5

library:
  source-dirs: src

  exposed-modules:
    - Foo

